### ISSUE TITLE
Ignition Platform update

### ISSUE THREAD

**Issue by pariaspe** [aerostack2-developers/ignition_platform#1]
List of TODO:
- [ ] Use templates for Ignition Bridge
- [ ] Read sensors from config file, not read them from ignition topics
- [ ] Remove unused parameters ("mas", "max_thrust" and "min_thrust")
- [ ] Add frame_id to odometry and ground truth messages
- [ ] Update sensors supported by Ignition Bridge
- [ ] Generate TF tree

**Comment by RPS98** [comment]
Not needed
